# DataFarme class


- 시리즈가 1차원 벡터 데이터에 행방향 인덱스(row index)를 붙인 것이라면 
- 데이터프레임 DataFrame 클래스는 2차원 행렬 데이터에 인덱스를 붙인 것과 비슷하다. 2차원이므로 각각의 행 데이터의 이름이 되는 행 인덱스(row index) 뿐 아니라 각각의 열 데이터의 이름이 되는 열 인덱스(column index)도 붙일 수 있다.

In [1]:
import numpy as np
import pandas as pd

## 데이터 프레임의 생성

In [6]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052], # 열1, 시리즈( 딕셔너리와 같다)
    "2010": [9631482, 3393191, 2632035, 2431774], # 열2, 시리즈
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]

#pd.DataFrame(시리즈  or 딕셔너리 데이터, index = 행인덱스, columns = 열인덱스)
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [5]:
data = np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [13]:
df.지역.values # df.'컬럼명'.values, 열인덱스 이름으로 열값 확인, 행은 불가능

array(['수도권', '경상권', '수도권', '경상권'], dtype=object)

In [10]:
df['2015'].values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [15]:
type(df['2015'])

pandas.core.series.Series

In [17]:
#만약 하나의 열만 빼내면서 데이터프레임 자료형을 유지하고 싶다면 
#원소가 하나인 리스트를 써서 인덱싱하면 된다.
df[['2015']]

2015
서울  9904312
부산  3448737
인천  2890451
대구  2466052

In [18]:
type(df[['2015']])

pandas.core.frame.DataFrame

In [12]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [19]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [21]:
# 전치
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

열 데이터의 갱신, 추가, 삭제

In [ ]:
# 갱신

In [22]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] *100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [23]:
# 추가
df['2020'] = [1,2,3,4]
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     1
부산  경상권  3448737  3393191  3512547  3655437           1.63     2
인천  수도권  2890451  2632035  2517680  2466338           9.82     3
대구  경상권  2466052  2431774  2456016  2473990           1.41     4

In [26]:
# 삭제
del df['2020']
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

## 열 인덱싱

In [12]:
df['지역'] # 결과는 시리즈

서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [27]:
df[['지역','2015']]  # 결과는 데이터프레임

특성   지역     2015
도시              
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [29]:
df[['지역']] #결과는 DataFrame

특성   지역
도시     
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [30]:
type(df['지역']), type(df[['지역']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

## 행 인덱싱


In [31]:
df[:'서울']

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83

In [32]:
df[1:2]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63

In [33]:
df['부산':'인천']

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [35]:
df.head(3)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [34]:
df.tail(3)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

## 개별 데이터 인덱싱


- df['열 이름']['행 이름']
- 데이터프레임의 개별인덱싱은 열행 순서!!!!!!!

In [36]:
df['2015']['서울'], df['2015'][0]

(9904312, 9904312)

## 연습문제 4.1.3

In [38]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [39]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

### (1) 모든 학생의 수학 점수를 시리즈로 나타낸다.

In [40]:
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

### (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.



In [41]:
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

### (3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.



In [42]:
df.values

array([[80, 90, 90],
       [90, 70, 60],
       [70, 60, 80],
       [30, 40, 70]], dtype=int64)

In [43]:
np.mean(df.values, axis=1).round(1)

array([86.7, 73.3, 70. , 46.7])

In [44]:
#평균 np.mean()
df['평균'] = np.mean(df.values, axis=1).round(1) #axis 1은 행, 0은 열

df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  40  70  46.7

- 연산의 대상이 2차원 이상인 경우에는 어느 차원으로 계산을 할 지를 axis 인수를 사용하여 지시한다. axis=0인 경우는 열 연산, axis=1인 경우는 행 연산이다. 디폴트 값은 axis=0이다. axis 인수는 대부분의 차원 축소 명령에 적용할 수 있다.

### (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.



In [45]:

del df['평균']
df['영어'][3] = 80
df['평균'] = np.round(df.mean(axis=1), 1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

### (5) 춘향의 점수를 데이터프레임으로 나타낸다.



In [46]:
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [49]:
df.head(1)

국어  영어  수학    평균
춘향  80  90  90  86.7

In [50]:

# 중간에 있는 두 행 꺼내오기
df.head(3).tail(2)

국어  영어  수학    평균
몽룡  90  70  60  73.3
향단  70  60  80  70.0

### (6) 향단의 점수를 시리즈로 나타낸다.

In [48]:
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64