# Numerical Python(Numpy) - Part1

- 파이썬의 고성능 과학 계산용 패키지

- 특징
<br>많은 숫자 데이터를 하나의 변수에 넣고 관리 할 때 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 
<br>1. 배열(array)을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다. 
<br>2. 배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.

모든 원소가 같은 자료형이어야 한다.

원소의 갯수를 바꿀 수 없다.

In [2]:
# de facto standard(사실상 표준)

import numpy as np

In [3]:
a =[1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
list(map(lambda x: 3*x, a))


[3, 6, 9]

In [5]:
b = np.array([1,2,3,])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional array, 차원형 배열

In [6]:
# np.array(), 넘파이 배열 생성 함수
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [7]:
type(a)

numpy.ndarray

In [8]:
# 데이터타입, 형태 확인 속성
a.dtype, a.shape

(dtype('float64'), (4,))

In [10]:
# numpy 배열의 shape은 항상 튜플로 표현된다.
# 빠른 계산이 목적이기 떄문에, 통일성을 강조한다.
# 하나의 데이터 타입만 배열에 넣을 수 있다.

## 2. Array shape

In [9]:
# Vector(1차원)
vector = np.array([1,4,5,8])
vector

array([1, 4, 5, 8])

In [11]:
vector.shape

(4,)

In [12]:
# Matrix(2차원)
matrix = np.array([[1,2,3,], [4,5,16]])
print(matrix.shape)
print(matrix)

(2, 3)
[[ 1  2  3]
 [ 4  5 16]]


In [16]:
# Tesonr(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [17]:
tensor.shape
#(면, 행, 열)

(2, 3, 4)

In [18]:
vector.shape, matrix.shape, tensor.shape



((4,), (2, 3), (2, 3, 4))

In [19]:
# size(), 넘파이 배열의 원소 개수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [12]:
# data type
# float32: 32bit, 
# float64: 64bit

a =np.array([1,2,3], dtype = np.float32)
a

array([1., 2., 3.], dtype=float32)

In [21]:
b = np.array([1,2,3], dtype = np.int32)

## reshape

In [22]:
# reshape, 배열 형태 확인
matrix.shape



(2, 3)

In [23]:
# reshape(), 넘파이 배열 형태 재정의
matrix.reshape(3, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5, 16]])

In [24]:
# reshape함수의 인수 "-1"

matrix.reshape(-1, )

# -1은 사이즈가 맞는 수를 자동으로 맞춰준다.

array([ 1,  2,  3,  4,  5, 16])

In [25]:
matrix.reshape(3,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5, 16]])

In [29]:
tensor.reshape(4,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [30]:
matrix.reshape(-1,)


array([ 1,  2,  3,  4,  5, 16])

In [31]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5, 16]])

In [32]:
matrix.reshape(-1,1)


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [16]])

## flatten
- 1차원 배열 변환 함수

In [53]:
tensor.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [54]:
tensor.flatten()
# a2 = tensor.ravel() # 또는 a2 = tensor.reshape(-1) 또는 a2 = tensor.flatten() 모두동일
#flatten()은 원본 값을 복사, 나머지는 복사 X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing &Slicing


### indexing


In [33]:
matrix

array([[ 1,  2,  3],
       [ 4,  5, 16]])

In [55]:
matrix[0][1]

2

In [56]:
matrix[0,1]

2

### slicing


In [13]:
# b =np.arrnge(16).reshpe(4,-1)
print(b)
b = np.arange(16).reshape(4,-1)
b

[1 2 3]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
# 5,6,7,9,10, 11

b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [37]:
#1, 3, 9, 11
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [38]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
# x는 앞에 3열, y는 마지막 열
X, y = b[:, : -1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))